### ISSUE TITLE
Can't use an enum as an Arg

### ISSUE THREAD

**Issue by Ulrar** [andreas/ocaml-graphql-server#106]
Hi,

Still new at graphql (and ocaml, for that matter), but I think there's something wrong with ~args : 

```ocaml
 io_field "projects"
   ~typ:(non_null (list (non_null project)))
   ~args:Arg.
     [ arg  "status" ~typ:status
     ]
   ~resolve:
     (fun () () st -> ...
```

I've been using the status type as an enum in the schema without any issues, except there in arg where it triggers that error when building : 
```
Error: This expression has type
         ('a, Project.status option) Graphql_lwt.Schema.typ
       but an expression was expected of type
         'b Graphql_lwt.Schema.Arg.arg_typ
```

Using a regular type like string seems to "solve" it, but I believe I should be able to use an enum there, am I mistaken ?
Thanks

**Comment by anmonteiro** [comment]
@Ulrar You can definitely use enums as arguments, but the types must concur. An `Arg.enum` is different than a `Schema.enum` and must be constructed differently.

Here's an example taking the `examples/server.ml` in this repo as a starting point:

```ocaml
type role = User | Admin

let role_enum_values = [
    Schema.enum_value "USER" ~value:User ~doc:"A regular user";
    Schema.enum_value "ADMIN" ~value:Admin ~doc:"An admin user";
  ]

let role = Schema.(enum "role"
  ~values:role_enum_values
)

let roleArg = Schema.Arg.enum "role" ~values:role_enum_values
```

Then you can use `roleArg` as the `typ` in your argument definition.

**Comment by Ulrar** [comment]
Okay, that does work ! Didn't think of looking in examples, I was using the readme. My bad, thanks !
