### ISSUE TITLE
Parsing error message

### ISSUE THREAD

**Issue by Ulrar** [andreas/ocaml-graphql-server#110]
Hi,

I'm having a weird issue with `Graphql_parser.parse` returning an Error ": string". What could that mean ? The query is fairly simple.
I have that error only when I receive the query from cohttp. I tried logging it to the console, copying that and passing that directly myself to parse and it processes it without any errors.

So apparently I get that weird ": string" error only if I get the query from the cohttp body, there must be something strange that doesn't show up in the console, but what .. Still, the error message doesn't seem very helpful, and I don't really understand where it's coming from.

EDIT : The query looks like that, btw
```
query {\n  projects {\n    name\n   }\n}
```
It's generated by elm-graphql, I've tried removing those \n but it doesn't change anything. As mentioned, running that works, unless it comes from cohttp.

**Comment by rrosenzweig** [comment]
Could you share the query please?

**Comment by Ulrar** [comment]
Added in an edit

**Comment by rrosenzweig** [comment]
Do you experience this issue when using GraphiQL? Can you replicate using curl too?

Assuming you use `Graphql_lwt.Server`, could you copy/paste from stdout when running the query please?

**Comment by Ulrar** [comment]
I don't understand how to use GraphiQL to query my app, or at least not the live demo thing.
I don't use Graphql_lwt.Server, I'm on mirageOS so I start cohttp manually.

But this (sorry for the mess but it's in a couple of functions, in my code) : 
```ocaml
body
|> Cohttp_lwt.Body.to_string
>>= Lwt.wrap1 Yojson.Basic.from_string
>>= fun j -> Yojson.Basic.Util.member "query" j
|> Yojson.Basic.to_string
|> fun q ->
Printf.printf "%s\n" q; flush stdout;
match Graphql_parser.parse q with
  | Ok query ->
      Schema.execute schema () query
      >>= fun r ->
        begin
          match r with
            | Ok r' -> Lwt.return (Yojson.Basic.to_string r')
            | Error err -> failwith (Yojson.Basic.to_string err)
        end
  | Error err -> Printf.printf "err : \"%s\"\n" err; flush stdout; Lwt.return err

```
Outputs that : 
```
"query {  projects {    name    }}"
err : ": string"
```
You can see that I get an Error ": string" from parse.
As mentioned, copying that from the console and feeding it to parse works just fine.

I can replicate with curl, yes : 
```bash
curl localhost:3000/graphql -X POST -d "{query:\"query {  projects {    name    }}\"}"
```

**Comment by Ulrar** [comment]
Writing this I just realized my mistake I think, to_string puts quotes around the query ..

**Comment by rrosenzweig** [comment]
@Ulrar Glad you found the issue. I do agree on the poor error message. Have you considered using `Graphql_lwt.Server`?
