### ISSUE TITLE
How to declare Arg.obj's coerce

### ISSUE THREAD

**Issue by Ulrar** [andreas/ocaml-graphql-server#111]
Hi,

I'm trying to figure out mutations, for which the only doc as far as I can tell seems to be #24.
To take an object as an argument (Schema.Arg.obj), it looks like you have to provide a coerce function, but the only indication is that it has to be of type 'b.

Is there any examples of projects using this lib I could take a look at ? Or any doc I might have missed ? Looking at the sources it seems like 'b is a function to convert from json, but I might be wrong since it doesn't seem to compile with that.

Thanks

**Comment by Ulrar** [comment]
Just realized the example directory has an example of Arg, it's not specific to mutations.
Still would be interested if you know any other projects using the lib to take a look at

**Comment by rrosenzweig** [comment]
Thanks for pointing out this shortcoming in the documentation -- I'll try add something about argument objects to the `README`.

Here's a brief summary:

```ocaml
val obj : ?doc:string ->
          string ->
          fields:('a, 'b) arg_list ->
          coerce:'b ->
          'a option arg_typ
```

`coerce` should be a function that accepts the arguments defined in `fields` and returns some value `'a`. A value of type `'a` will be exposed to the `resolve` function of the field where the argument is used.

```ocaml
type person = {
  name : string;
  age : int;
}

(* person Schema.Arg.arg *)
let person_arg = Schema.Arg.(obj "Person"
  ~fields:[
    arg "name" ~typ:(non_null string);
    arg "age" ~typ:(non_null int)
  ]
  ~coerce:(fun name age ->
    (* name has type string, and age has type int *)
    { name; age }
  )
)

(* (unit, unit) Schema.field *)
let field = Schema.(field "greeter"
  ~typ:(non_null string)
  ~args:Arg.[
    arg "person" ~typ:(non_null person_arg))
  ]
  ~resolve:(fun () () p ->
    (* p has type person *)
    Format.sprintf "Hello %s, age %d" p.name p.age
  )
)
```

Does that answer your question?

**Comment by Ulrar** [comment]
Yes, seems to be working ! Thanks for the clear explanations.

Unrelated question, but I might as well avoid an issue just for that, is ~resolve's return in mutation fields used for anything ? I'm trying to process that query : 

```
mutation ($status: status!, $name: String!) {  addProject(project: {name: "test", desc: "vcv", status: OPEN}) {    project(status: $status, name: $name) {      name      desc      status    }  }}
```
The mutation does happen fine, it gets saved, but neither returning the object in the mutation io_field's resolve neither defining a regular "project" field seems to work, I always get a null project in the response. It looks like the query at the end of that mutation just gets ignored

**Comment by rrosenzweig** [comment]
That sounds puzzling. Can you share the definition of the mutation field `addProject` please?

**Comment by Ulrar** [comment]
```ocaml
~mutations:
  [ io_field "addProject"
    ~typ:(non_null project)
    ~args:Arg.[arg "project" ~typ:(non_null projectArg)]
    ~resolve:
      (fun () () p ->
        Project.saveNew (module Store) p
        >>= fun () -> Lwt.return p
      )
  ]
```

I've tried a few things, including just returning the project as is like here, but I always end up with null in the response. I've also added a field "project" in the schema, but it never gets called either.

**Comment by Ulrar** [comment]
Okay nevermind, I've figured it out again. My query expects a project field, but the mutation returns the object itself, not encompassed in an other object.
Sorry for the noise, slowly figuring it out :)
