### ISSUE TITLE
Guidance for integrating with existing Opium/Other server. 

### ISSUE THREAD

**Issue by anisjonischkeit** [andreas/ocaml-graphql-server#121]
I have an existing Opium server and just want one of my endpoints to be graphql. If anyone can point me in the right direction for this I'd be really appreciative.

Also sorry in advance if this is the wrong place to ask.

**Comment by anmonteiro** [comment]
Here's an example that you could copy: https://github.com/andreas/ocaml-graphql-server/blob/cad6b3c6bf542ac5d848631dc3846ea08be70c1b/graphql-lwt/src/graphql_lwt.ml#L31-L54

**Comment by andreas** [comment]
There's no proper integration between `opium` and `ocaml-graphql-server` right now. Copying some of the code from `Graphql_lwt.Server` will be the quickest way to get going (what @anmonteiro mentioned).

There's previously been talk about exposing a function á la `'ctx Graphql_lwt.Schema.t -> 'ctx -> Cohttp.Request.t -> Cohttp.Body.t -> (Yojson.Basic.json, Yojson.Basic.json) result Lwt.t`, which seems like it would be helpful in this scenario as well, but it's not there yet.

**Comment by anisjonischkeit** [comment]
Thanks for the guidance, it's really helped. Just thought I'd show what I came up with in-case someone else gets stuck with this.

```ocaml
open Opium.Std
open Graphql_lwt

type user = { 
  id : int;
  name : string;
} 
  
let alice = { id = 1; name = "Alice" }
and bob = { id = 2; name = "Bob"}
 
let users = [alice; bob]

let user = Schema.(obj "user"
  ~fields:(fun _user -> [
    field "id"
      ~args:Arg.[]
      ~typ:(non_null int)
      ~resolve:(fun () p -> p.id)
    ;
    field "name"
      ~args:Arg.[]
      ~typ:(non_null string)
      ~resolve:(fun () p -> p.name)
    ;
  ])
)

let schema = Schema.(schema [
    io_field "users"
      ~args:Arg.[]
      ~typ:(non_null (list (non_null user)))
      ~resolve:(fun () () -> Lwt_result.return users)
    ;
  ])


let json_err = function
  | Ok _ as ok -> ok
  | Error err -> Error (`String err)

let execute_query ctx schema variables operation_name query =
  let open Lwt_result in
  Lwt.return @@ json_err @@ Graphql_parser.parse query >>= fun doc ->
  Schema.execute schema ctx ~variables ?operation_name doc

let respondYoJson ?headers ?(code=`OK) body =
    let open Lwt in
    let content_type ct h = Cohttp.Header.add_opt h "Content-Type" ct in
    Response.of_string_body
        ~code
        ~headers:(content_type "application/json" headers) 
        (Yojson.Basic.to_string body)
    |> return 


let graphqlEndpoing = post "/graphql" begin fun req ->
  let open Lwt in
  App.string_of_body_exn req >>= fun req_body ->
    let result = execute_query () schema [] None req_body in
    result >>= function
      | Ok data ->
          respondYoJson data

      | Error err ->
          respondYoJson err
end


let () =
  App.empty
  |> graphqlEndpoing
  |> App.run_command  
```

Also any suggestions for improvement are appreciated.

**Comment by andreas** [comment]
Thanks for sharing @anisjonischkeit! I'll close this issue for now, but will make a mental note of another vote for a "request handler function" :)
