### ISSUE TITLE
CORS?

### ISSUE THREAD

**Issue by sporto** [andreas/ocaml-graphql-server#129]
Hi. Does this support CORS? I could't find any mention of it or headers like `Access-Control-Allow-Origin`.

Could you give me an example of setting the CORS headers?

Thanks

**Comment by anmonteiro** [comment]
This library provides an example server that doesn't allow you to customize the response headers: 
https://github.com/andreas/ocaml-graphql-server/blob/4367e7ffec6d9b083bd1093a287b9f53a6e78cc3/graphql-lwt/src/graphql_lwt.ml#L44-L46

However, as I found in my own projects, that is not enough and you'll need to write your own server that calls into the constructs provided by `Graphql_schema`. This function is a good starting point to writing your own:

https://github.com/andreas/ocaml-graphql-server/blob/4367e7ffec6d9b083bd1093a287b9f53a6e78cc3/graphql-lwt/src/graphql_lwt.ml#L31

**Comment by andreas** [comment]
Adding custom HTTP headers to the response will be a lot easier once this PR is merged: https://github.com/andreas/ocaml-graphql-server/pull/126

In the meantime you can either take the approach described by @anmonteiro, or have Nginx in front and add CORS headers there (that's what I do).

**Comment by anmonteiro** [comment]
`graphql-cohttp` is now a thing. This can probably be closed?

**Comment by andreas** [comment]
I'll close this one. Feel free to open a PR against `graphql-cohttp` with CORS support 😄
