### ISSUE TITLE
curt parser error

### ISSUE THREAD

**Issue by joprice** [andreas/ocaml-graphql-server#137]
The error shown when parsing some incomplete queries differs from others:

`"{\n#test \n\n"`

returns the error ': string'

Making the comment a single letter changes the message:

`"{\n#t \n\n"`

returns the error ': not enough input'

I ran into this using graphiql since it includes a mix of extra whitespace and comments.

**Comment by anmonteiro** [comment]
@joprice the errors should be different in master, since the parser implementation was replaced in #132

**Comment by joprice** [comment]
I tested it with the following resolutions: 

```
  "@opam/graphql": "andreas/ocaml-graphql-server:graphql.opam#508c5a2d0256d5201932d78b3aacadb87c4ee55f",
  "@opam/graphql-lwt": "andreas/ocaml-graphql-server:graphql-lwt.opam#508c5a2d0256d5201932d78b3aacadb87c4ee55f",
```

**Comment by anmonteiro** [comment]
Here are the errors for your examples in master:

```
Failed to parse {
#test

: Line 4 col 1: Syntax error.
```

```
 Error Failed to parse {
#t

: Line 4 col 1: Syntax error.
```

**Comment by joprice** [comment]
I was missing a resolution for the parser. Didn't realize transitive dependencies weren't automatically overridden by esy. Adding this made it work

`"@opam/graphql_parser": "andreas/ocaml-graphql-server:graphql_parser.opam#508c5a2d0256d5201932d78b3aacadb87c4ee55f",`
