### ISSUE TITLE
`[ERROR] No package named graphql-cohttp found.` when use `opam install graphql-cohttp`

### ISSUE THREAD

**Issue by cepalle** [andreas/ocaml-graphql-server#138]
Hello,

I try to use ocaml-graphql-server in Ubuntu 18.04.1, but I get :

```
➜  examples opam install graphql-cohttp
[ERROR] No package named graphql-cohttp found.
➜  examples ocaml --version
The OCaml toplevel, version 4.05.0
➜  examples opam --version
1.2.2
```

In README file, in API documentation section, the `graphql-cohttp` link is dead.

`graphql`, `graphql-lwt`, `graphql-async` and `graphql_parser` packages seems work.

**Comment by anmonteiro** [comment]
`graphql-cohttp` is not released to OPAM yet, you can use a local pin for now.

AFAIU Andreas was waiting until Cohttp 2.0 was released (which it now has been) to release it.
