### ISSUE TITLE
No implementations of Digestif on MacOS

### ISSUE THREAD

**Issue by sporto** [andreas/ocaml-graphql-server#142]
Hi
While trying to run the example on Mac OS I'm getting

```
Error: No implementations provided for the following modules: Digestif
 referenced from  ... graphql_cohttp-opam__c__0.10.0-f69e42b3/lib/graphql-cohttp/graphql_cohttp.cmxa(Websocket)
```

Any idea on how to fix this dependency on MacOS? Thanks

**Comment by andreas** [comment]
Thanks for reporting this! I've just pushed a fix (for the curious: `digestif` requires you to pick between the C and the OCaml implementation). Please try again and let me know if there are any issues.

**Comment by sporto** [comment]
Thanks, this works
