### ISSUE TITLE
Allow defining multiple graphql end point paths

### ISSUE THREAD

**Issue by sporto** [andreas/ocaml-graphql-server#143]
Hi

I want to make two graphql end points in my app. One is for public (non authenticated) users. And the other one for Authenticated users. e.g. `/graph-public` and `/graph-app`.  Each using different schemas.

I have done this pattern several times with other GraphQL servers and it simplifies the handler of context quite a lot. e.g. in the authenticated end point you always have a user in the context.

From here https://github.com/andreas/ocaml-graphql-server/blob/master/graphql-cohttp/src/graphql_cohttp.ml#L104 it looks like this cannot be configured.

Thanks

**Comment by andreas** [comment]
Hi @sporto,

The line you point to is the built-in Cohttp callback which is intended for development/testing purposes. `Graphql_cohttp` exposes the necessary functions to allow you to do custom routing with any number of schemas.

Here's a simple example that should get you going (untested!):

```ocaml
let public_schema = (* ... *)
let app_schema = (* ... *)

let make_context req = (* ... *)

module Graphql_cohttp_lwt = Graphql_cohttp.Make (Graphql_lwt.Schema) (Cohttp_lwt_unix.IO) (Cohttp_lwt.Body)

let callback _conn req body =
  let req_path = Cohttp.Request.uri req |> Uri.path in
  let path_parts = Str.(split (regexp "/") req_path) in
  match req.meth, path_parts with
  | `POST, ["graph-public"]  -> Graphql_cohttp_lwt.execute_request public_schema  (make_context req) req body
  | `POST, ["graph-app"]     -> Graphql_cohttp_lwt.execute_request app_schema (make_context req) req body
  | _ -> respond_string ~status:`Not_found ~body:"" ()

let () =
  let on_exn = function
    | Unix.Unix_error (error, func, arg) ->
      Logs.warn (fun m ->
        m  "Client connection error %s: %s(%S)"
          (Unix.error_message error) func arg
      )
    | exn -> Logs.err (fun m -> m "Unhandled exception: %a" Fmt.exn exn)
  in
  let server = Cohttp_lwt_unix.Server.make_response_action ~callback () in
  let mode = `TCP (`Port 8080) in
  Cohttp_lwt_unix.Server.create ~on_exn ~mode server
  |> Lwt_main.run
```

**Comment by sporto** [comment]
Great, that is very helpful, thanks
I'm having a bit of trouble with `respond_string`. Don't know where `Io` comes from.
Maybe `respond_string` could be exposed?

**Comment by andreas** [comment]
> I'm having a bit of trouble with `respond_string`. Don't know where `Io` comes from.

Good point, I've rewritten the example to not use `respond_string` now.

**Comment by sporto** [comment]
Great thanks, this works like a charm
