### ISSUE TITLE
Typechecking queries?

### ISSUE THREAD

**Issue by apatil** [andreas/ocaml-graphql-server#16]
Hi @andreas, is there a way to verify that a query is compatible with the server's schema? I'm wondering if it's possible to write a js_of_ocaml client that shares some code with the server, in such a way that any incompatible queries are caught by the typechecker.

**Comment by andreas** [comment]
That's certainly an appealing idea. It seems something like what you propose exists in the Javascript world (though that's at runtime, not compile time):

- https://www.npmjs.com/package/@creditkarma/graphql-validator
- https://dev-blog.apollodata.com/graphql-js-the-hidden-features-effaca7a81b3#.ylmf3zhs7

Currently there's no such functionality in `ocaml-graphql-server`. I'm prioritising getting basic features done first (variable support, mutation support and improving the parser), but I'd be happy to help out if it's something you would like to work on 😄

**Comment by andreas** [comment]
Closing this issue in favor of #36.
