### ISSUE TITLE
Operation not found

### ISSUE THREAD

**Issue by sync** [andreas/ocaml-graphql-server#160]
When using latest code direction from master and if I query my server with the following query, It works when using the opam release:

```
{
  links {
    id
    url
  }
}

```

I get

```
{
  "errors": [
    {
      "message": "Operation not found"
    }
  ]
}
```

I can get it to work when doing this:

```
query Blah {
  links {
    id
    url
  }
}
```

```
{
  "data": {
    "links": [
      {
        "id": 2,
        "url": "http://dev.apollodata.com/"
      },
      {
        "id": 1,
        "url": "http://graphql.org/"
      }
    ]
  }
}
```

Could this PR be the culprit ? 
https://github.com/andreas/ocaml-graphql-server/pull/156

I am also using the default `Graphql_cohttp_lwt`

**Comment by sync** [comment]
Same query work if I use GraphQL Playground, only happen when using the builtin graphiQL that comes with Graphql_cohttp

**Comment by andreas** [comment]
Sounds likely with #156. Thanks for reporting, I’ll take a look!

**Comment by andreas** [comment]
I can replicate what you experience when GraphiQL sends `operationName=undefined` for some reason. Is that what happens in your case also? Can you provide more details about the HTTP request which causes the error (e.g. copy as cURL from the Chrome network tab).

**Comment by sync** [comment]
I am sorry I completely forgot to get back to you and will do it first thing in the morning

**Comment by osener** [comment]
I've seen this before, I suspect a GraphiQL bug as it goes away when I press <kbd>Prettify</kbd>.

**Comment by sync** [comment]
Yes just tried and cannot reproduce it on https://anthonymittaz.com/graphql?query=%7B%0A%20%20links%20%7B%0A%20%20%20%20id%0A%20%20%20%20url%0A%20%20%7D%0A%7D

**Comment by sync** [comment]
tried again on my main computer but can't reproduce. So i guess we are all good and there isn't anything to fix ?

**Comment by sync** [comment]
perhaps i should spend some time upgrading graphiQL and send a PR, would you happy for me to do so ?

**Comment by sync** [comment]
i also have a ssl (wss) bug fix for web socket connection when using https, the logic in the code always trying to connect to a non secure web socket connection

**Comment by andreas** [comment]
Sure, that would be great 😊

**Comment by andreas** [comment]
I'll close this for now -- please reopen if still relevant 😄
