### ISSUE TITLE
Fields defined in fragments don't merge properly

### ISSUE THREAD

**Issue by dwwoelfel** [andreas/ocaml-graphql-server#167]
If fields are defined in a fragment, they won't be merged properly with the rest of the fields.

Example:

```
query Films {
  allFilms {
    films {
      title
    }
  }
  ...F
}

fragment F on Root {
  allFilms {
    films {
      episodeID
    }
  }
}
```

Should return (see [swapi example](https://graphql.org/swapi-graphql/?query=query%20Films%20%7B%0A%20%20allFilms%20%7B%0A%20%20%20%20films%20%7B%0A%20%20%20%20%20%20title%0A%20%20%20%20%7D%0A%20%20%7D%0A%20%20...F%0A%7D%0A%0Afragment%20F%20on%20Root%20%7B%0A%20%20allFilms%20%7B%0A%20%20%20%20films%20%7B%0A%20%20%20%20%20%20episodeID%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D))
```
{
  "data": {
    "allFilms": {
      "films": [
        {
          "title": "A New Hope",
          "episodeID": 4
        },
      ]
    }
  }
}
```

But in ocaml-graphql-server, it will drop the episodeID
```
{
  "data": {
    "allFilms": {
      "films": [
        {
          "title": "A New Hope"
        },
      ]
    }
  }
}
```

Created a branch with a failing test here: https://github.com/andreas/ocaml-graphql-server/compare/master...dwwoelfel:fragment-handling

**Comment by andreas** [comment]
Thank for raising this -- and the reproduction case! I'll try look into it later this week.
