### ISSUE TITLE
ocamlformat

### ISSUE THREAD

**Issue by naartjie** [andreas/ocaml-graphql-server#173]
Would you accept a PR to add `ocamlformat` to the project? If so, any preference for profile?

I was thinking of just adding the project files, and @andreas could run `dune build @fmt --auto-promote`. I wouldn't want to be the main committer.

Anyways, let me know if you'd be keen, if so, I can do a couple of disposable PR's with the different profiles, just to preview what the code would end up like with each of them.

**Comment by andreas** [comment]
I've been wanting to adopt `ocamlformat` for a while, but never got around to investigating the format options. I would imagine going for `conventional` or `ocamlformat`. If you want to help out investigating and trying something out, I'd appreciate it 😄

**Comment by andreas** [comment]
Thanks for creating those PRs! I'm inclined to use `conventional`. Do you happen to know if there's a good way to enforce the `ocamlformat` style with CI, i.e. fail the build if the formatting does not conform?

**Comment by cem2ran** [comment]
@andreas you could consider adding this as a pre-commit hook?

**Comment by andreas** [comment]
> @andreas you could consider adding this as a pre-commit hook?

Yeah, I guess that could be a start.

**Comment by anmonteiro** [comment]
> Do you happen to know if there's a good way to enforce the ocamlformat style with CI, i.e. fail the build if the formatting does not conform?

This is what I do in H2:

https://github.com/anmonteiro/ocaml-h2/blob/a0a916a4b7b21b9fa3abe1a89c946207f15c270a/.circleci/config.yml#L108-L109

**Comment by naartjie** [comment]
@anmonteiro 

+1 for @anmonteiro's method of failing the build. H2 is using CircleCI, would just need to figure out how to run that check in travis.

**Comment by yawaramin** [comment]
Looks like this is closed by #177

**Comment by andreas** [comment]
Indeed, thanks!

**Comment by naartjie** [comment]
Thanks @yawaramin, I was keeping this open in order to take care of the CI check, but it's better to open a new issue for that 👍
