### ISSUE TITLE
subscriptions

### ISSUE THREAD

**Issue by DrYSG** [andreas/ocaml-graphql-server#188]
I see in your documentation how the schema is defined for subscriptions, but what transport are you doing subscriptions over? WebSockets? If I wanted to hook your code up with ReWeb, where would I look to do this?

more specifically, when I look at examples/server.ml I see a cohttp_lwt server, but I don't see how it is doing websockets for subscriptions.

**Comment by andreas** [comment]
Subscriptions are exposed via websockets following the protocol described in [`apollographql/subscriptions-transport`](https://github.com/apollographql/subscriptions-transport-ws/blob/master/PROTOCOL.md). I'm not sufficiently familiar with ReWeb to give advice about that, but you can see the websocket handler code [here](https://github.com/andreas/ocaml-graphql-server/blob/940e86f9ff1a017be2ff64b3a35c71804d9a4729/graphql-cohttp/src/graphql_cohttp.ml#L175-L183) for `graphql-cohttp`.

**Comment by andreas** [comment]
Closing this for now... please re-open if you have further questions 😄
