### ISSUE TITLE
Asynchronous resolvers

### ISSUE THREAD

**Issue by andreas** [andreas/ocaml-graphql-server#2]
It should be possible to return a `Lwt.t` or `Async.t` from the `resolve`-function of a field. A likely solution is to functorize the execution over an `IO` monad.

**Comment by sgrove** [comment]
This seems pretty critical for any real OCaml app - even our DB queries are `Lwt.t`/`Async.t`.

**Comment by kennetpostigo** [comment]
I'd love to get this feature in. Was there any specific way you were looking to implement this?

**Comment by andreas** [comment]
I'm almost done with this feature, I expect to share something by the end of this week.

**Comment by sgrove** [comment]
Wow, that's very exciting. I have an immediate use case once it lands -
thank you!

**Comment by kennetpostigo** [comment]
@andreas Awesome! Really looking forward to this landing!

**Comment by andreas** [comment]
@kennetpostigo: would you be interested in porting [dataloader](https://github.com/facebook/dataloader) to OCaml/Reason now that there's support for asynchronous resolvers?

**Comment by kennetpostigo** [comment]
I could certainly try! This week I won't be able to but next week should have time.
