### ISSUE TITLE
Support for __typename

### ISSUE THREAD

**Issue by andreas** [andreas/ocaml-graphql-server#22]
https://facebook.github.io/graphql/#sec-Type-Name-Introspection

**Comment by sgrove** [comment]
Is this the same as (or can be derived from?) the `typ` argument at all for a field? Starting to do some queries where being able to dispatch off of some of the metadata would be useful

**Comment by andreas** [comment]
Yeah, that sounds right. Would you like to try your hand with this? Otherwise I should be able to add it rather quickly.

**Comment by sgrove** [comment]
I'm a bit intimidated to dive into the source, but it might be a good idea! Do you have some suggestions for how to go about it?

I think `non_null (list (non_null int))` should output `[Int!]!`. But for custom types, e.g. `non_null (list tweet)`, what would be the output and how would you generate it?

Hopefully I'll be able to contribute a bit more meaningfully if I take this on!

**Comment by andreas** [comment]
Please see #37 :)
