### ISSUE TITLE
How to return recursive schema types

### ISSUE THREAD

**Issue by sgrove** [andreas/ocaml-graphql-server#27]
In the included example, if we imagined one more field for users that contained their coworkers' ids:

```ml
type user = {
  id   : int;
  name : string;
  role : role;
  ip   : string;
  coworker_ids : int list;
}

let users = [
  { id = 1; name = "Alice"; role = Admin; ip = "unresolved"; coworker_ids = [1]};
  { id = 2; name = "Bob"; role = User; ip = "unresolved"; coworker_ids = [2]};
  { id = 3; name = "Carol"; role = Admin; ip = "unresolved"; coworker_ids = []}
]
```

How would we modify the `user` definition to add a coworkers field?

```ml
let rec user = Schema.(obj
  ~name:"user"
  ~fields:[
      field "coworkers"
      ~args:Arg.[]
      ~typ:(non_null (list (non_null user)))
      ~resolve:(fun () p ->
      let other_ids = p.coworker_ids in
      let others = List.map (fun id -> List.find (fun worker -> worker.id = id) users) other_ids in
      others
      )
  ;
```

Specifically, I get this error with the above code: `Error: This kind of expression is not allowed as right-hand side of 'let rec'`

**Comment by sgrove** [comment]
After chatting on freenode #ocaml a bit, I got this from Drup:

> Given how the library is made, the short answer is that you can't. The library need to allow to break the recursivity (by declaring unfinished objects) or providing the fixpoint combinator (which is usually quite annoying to use)

Sounds like it might not be such a straightforward fix :)

**Comment by andreas** [comment]
Thanks for uncovering this -- I hadn't given too much thought and naively figured it could be solved with `let rec`. I'll look into a proper solution.

**Comment by andreas** [comment]
I've come up with a solution now that mirrors the experience from other GraphQL libraries: rather than provide a list of fields directly, `~fields` is a function that receives the object itself as an argument. Example:

```ocaml
type user = {
  name : string;
  friends : user list;
}

let rec alice = { name = "Alice"; friends = [bob] }
    and bob = { name = "Bob"; friends = [alice] }

let users = [alice; bob]

let role = Schema.enum
  ~name:"role"
  ~values:[(User, "user"); (Admin, "admin")]

let user = Schema.(obj
  ~name:"user"
  ~fields:(fun user -> [ (* <-- NEW *)
    field "name"
      ~args:Arg.[]
      ~typ:(non_null string)
      ~resolve:(fun () p -> p.name)
    ;
    field "friends"
      ~args:Arg.[]
      ~typ:(list (non_null user))
      ~resolve:(fun () p -> Some p.friends)
    ;
  ])
)
```

I'm considering whether the library should provide two object construction functions (one for providing a simple list of fields, and another for providing a function), or just always force the user to provide a function for `~fields`. E.g.

```ocaml
(* Option 1: Two object construction functions *)
  val obj : name:string ->
            fields:('ctx, 'src) field list ->
            ('ctx, 'src option) typ

  val recursive_obj : name:string ->
                      fields:(('ctx, 'src option) typ -> ('ctx, 'src) field list) ->
                      ('ctx, 'src option) typ

(* Option 2: Always force the user to provide a function for fields *)
  val obj : name:string ->
            fields:(('ctx, 'src option) typ -> ('ctx, 'src) field list) ->
            ('ctx, 'src option) typ
```

Any thoughts?
