### ISSUE TITLE
Introspection query should contain argument default value

### ISSUE THREAD

**Issue by andreas** [andreas/ocaml-graphql-server#31]
Currently the `defaultValue`-field of `__InputValue`-type is always `null` in introspection query results. It should be populated as [per the spec](https://facebook.github.io/graphql/#sec-The-__InputValue-Type).

**Comment by dwwoelfel** [comment]
I've been looking at this, and I think the best approach would be to change the type of `~default` in `arg'` from `'a` to `Graphql_parser.const_value`. From there, you can call `string_of_const_value` to get the `defaultValue` field in the introspection query and `eval_arg` to get the same value of type `'a` that is currently passed to `~default`.

Example

Before
```ocaml
arg' "someArg" ~typ:string ~default:"defaultString"
```

After
```ocaml
arg' "someArg" ~typ:string ~default:(`String "defaultString")
```

I looked at deriving a `Graphql_parser.const_value` from the `~default` arg, but the `~coerce` function for an input object loses information, so I don't think it would be possible to derive the `const_value`.

Example:

```ocaml
let argObj =
  Arg.obj "InputObject"
     ~fields:Arg.[(arg "argOne" ~typ:int); (arg "argTwo" ~typ:int)] 
     ~coerce:(fun arg_one arg_two -> arg_one + arg_two) in
arg' "inputArg" ~typ:argObj ~default:3
```

That `defaultValue` in that case could be either `{a: 1 b: 2}` or `{a: 3 b: 0}`.

With the default as const_value approach, this would be defined as

```ocaml
arg' "inputArg" ~typ:argObj ~default:(`Assoc [("a", `Int 1); ("b", `Int 2)])
```

One downside of this approach is that you can't ensure that `~default` is correct at compile-time. I think it should be possible at schema construction time or at introspection-query time at the very least.
