### ISSUE TITLE
Example of cursor implementation for pagination

### ISSUE THREAD

**Issue by sgrove** [andreas/ocaml-graphql-server#34]
I haven't tried it yet, but I'm curious how you might implement cursors right now. Would the resolving functions have a way to get a reference to one passed in right now via #20 perhaps?

As a reference, it's worth looking at Apollo's cursor examples http://dev.apollodata.com/react/pagination.html#cursor-pages

**Comment by andreas** [comment]
Implementing cursor-based pagination should be similar to other GraphQL servers. Basically a cursor argument should encode all data required for fetching a particular page of objects, and the return object should contain a cursor for the next page.

Here's a dummy example similar to the Apollo link:

```ocaml
module Comments : sig
  type page = {
    cursor : string;
    comments : comment list;
  }

  val find_page : cursor:string option -> page option
end = struct
  (* ... *)
end

let comment_page = Schema.(obj
  ~name:"CommentPage"
  ~fields:(fun _ -> [
    field "cursor"
      ~typ:(non_null string)
      ~args:Arg.[]
      ~resolver:(fun ctx page -> page.cursor)
    ;
    field "comments"
      ~typ:(list (non_null comment))
      ~args:Arg.[]
      ~resolver:(fun ctx page -> page.comments)
  ])
)

let schema = Schema.(schema ~fields:[
  field "moreComments"
    ~typ:comment_page
    ~args:Arg.[
      arg "cursor" ~typ:string;
    ]
    ~resolver:(fun ctx () cursor ->
      Comments.find_page ~cursor
    )
])
```

**Comment by andreas** [comment]
I'm going to close this, but feel free to ask more questions.

**Comment by johnwu93** [comment]
Here is an example of a real-life project using pagination for OCaml GraphQL:
https://github.com/CodaProtocol/coda/blob/73353f9e3d3fc13095be24f2d5e29552d1f8315e/src/app/cli/src/graphql.ml#L438

**Comment by andreas** [comment]
Thanks for sharing, @johnwu93 😄
