### ISSUE TITLE
`-` in string argument causes error

### ISSUE THREAD

**Issue by sgrove** [andreas/ocaml-graphql-server#41]
I have an field that takes a string argument, and simply putting in `"-"` is enough to trigger the error:  `": string"`. Also, any japanese/chinese/etc. input causes the same error.

Any idea what's causing this?

**Comment by andreas** [comment]
Could you try update to the latest master? I recently fixed string parsing (#39).

**Comment by sgrove** [comment]
Yup, looks like master fixes it for this input. Thank you!
