### ISSUE TITLE
Remove optional dependencies

### ISSUE THREAD

**Issue by rgrinberg** [andreas/ocaml-graphql-server#44]
I've explained why optional dependencies should be avoided here: http://rgrinberg.com/posts/optional-dependencies-considered-harmful/ and I think the quickest way to fix the problem in graphql's case is to port the package to jbuilder. If you want, I can submit an initial port.

**Comment by sgrove** [comment]
I've been hoping to play with  jbuilder at some point, maybe having this project converted over would be the impetus :)

**Comment by andreas** [comment]
An initial port to jbuilder would be much appreciated -- thanks! 😊

**Comment by andreas** [comment]
Closed by #50
