### ISSUE TITLE
Graphiql Error: {"errors":[{"message":"No operation found"}]}

### ISSUE THREAD

**Issue by sgrove** [andreas/ocaml-graphql-server#46]
Working with `graphiql` `0.10.6`, I see `Error: {"errors":[{"message":"No operation found"}]}` when starting up. I'm not sure what's changed to cause the error though, and having some trouble tracking it down.

**Comment by sgrove** [comment]
Seems to be caused by named queries (if that's the correct term).

This works:

```
query {
   id
}
```
This triggers the error:

```
  query NamedSomething {
   id
  }
```

This also means that top-level queries with variable won't work, e.g.:

```
query getUserAndLikes($id: ID!) {
  user(userId: $id) { name }
  likes(userId: $id) { count }
}
```

**Comment by andreas** [comment]
Thanks for reporting this issue. I'll have a fix out soon.
