### ISSUE TITLE
Deprecate fields

### ISSUE THREAD

**Issue by sgrove** [andreas/ocaml-graphql-server#49]
The spec says we should be able to deprecate fields https://facebook.github.io/graphql/#sec-Deprecation by two fields: `isDeprecated` and `deprecationReason`. Any idea how we would express this in ocaml-graphql-server?

**Comment by andreas** [comment]
It's currently not supported. I imagine adding an optional argument `?deprecated` to the definition of `Graphql.Schema.field`:

```ocaml
type deprecated =
  | NotDeprecated
  | Deprecated of string option

val field :
  ?deprecated:deprecated ->
  (* ... *)
```
