### ISSUE TITLE
Docs on individual enum values

### ISSUE THREAD

**Issue by sgrove** [andreas/ocaml-graphql-server#51]
Is it possible to add documentation to the enum values themselves?

Right now it's an associative list:

```
let twitterSearchOrderResult =
  Schema.enum
    "order"
    doc::"Specifies how to order the search results"
    values::[
      (Date, "date"), /* Sort by date of the tweets */
      (LikeCount, "likeCount"), /* Sort by number of likes */
      (RetweetCount, "retweetCount"), /* Sort by number of retweets */
      (GraphDistance, "graphDistance"), /* Sort by how many steps in the twitter graph this user is from you */
      (GeoDistance, "geoDistance"), /* Sort by how far a tweet is from you geographically */
    ]
```

All of these examples are pretty straightforward (except GraphDistance, perhaps), but some have more nuanced implications about performance, meaning, intended usage, etc. Is there some way to move the comments into the schema so they'll show up tools like graphiql?

**Comment by andreas** [comment]
It's not possible right now, but I'll work on adding it.
