### ISSUE TITLE
Publish to opam

### ISSUE THREAD

**Issue by sgrove** [andreas/ocaml-graphql-server#52]
I think ocaml-graphql-server probably deserves a proper opam release! Are there any blockers to this? Perhaps the jbuilder PR will help?

**Comment by andreas** [comment]
Submitted! ✨ 

`graphql`: https://github.com/ocaml/opam-repository/pull/9309
`graphql-lwt`: https://github.com/ocaml/opam-repository/pull/9309
`graphql-async`: https://github.com/ocaml/opam-repository/pull/9310

**Comment by andreas** [comment]
Done! 🎊
