### ISSUE TITLE
Dynamically filter graphql schema

### ISSUE THREAD

**Issue by sgrove** [andreas/ocaml-graphql-server#57]
I'd like to be able to show some clients different schemas. For example, we have some internal dev fields that I don't want exposed to some clients (all under a single top-level key right now, but it could become arbitrarily more complicated than that), to the point they shouldn't even be able to introspect the schema for them (though we want to be able to from our dev clients).

How would you recommend going about this?

**Comment by andreas** [comment]
I would recommend passing different schemas to `Schema.execute` in the callback to `Cohttp.Server` depending on the request (e.g. [`examples/server.ml`](https://github.com/andreas/ocaml-graphql-server/blob/master/examples/server.ml#L79)). I imagine you would write a function `select_schema : Cohttp.Request.t -> ('ctx Schema.schema * 'ctx)` and use that like so:

```ocaml
(* Assume variables and doc have already been created*)
let schema, ctx = select_schema req in
Schema.execute schema ctx  ~variables doc
```

Would that work for you?

**Comment by andreas** [comment]
Closing this one for now. Feel free to reopen if you need more input.
