### ISSUE TITLE
Interface support

### ISSUE THREAD

**Issue by andreas** [andreas/ocaml-graphql-server#6]
See:

- https://facebook.github.io/graphql/#sec-Interfaces
- https://facebook.github.io/graphql/#sec-Interface
- https://facebook.github.io/graphql/#sec-Field-Selections-on-Objects-Interfaces-and-Unions-Types

**Comment by sgrove** [comment]
We're coming against a use case where we need interfaces as well, any thoughts on how to support this?

**Comment by andreas** [comment]
I have some ideas, but it's not straight forward. Could unions be used to solve the use case? I think they will be easier to implement.

**Comment by sgrove** [comment]
From the spec and https://medium.com/the-graphqlhub/graphql-tour-interfaces-and-unions-7dd5be35de0d, it looks like it. I gave a bit of an example in https://github.com/andreas/ocaml-graphql-server/issues/33#issuecomment-319062232, where we might have a number of `Url`s returned in a resolver, but as different types (`VideoUrl`, `CommentUrl`, `PlainUrl`, `DescriptionUrl`), and want to be able to traverse differently depending on the type:

```
{
  urls {
    __typename
    ... on VideoUrl {
      url {
        expandedText
        displayedText
        description
      }
      video {
        title
        user {
          email
        }
      }
    }
    ... on CommentUrl {
      url {
        expandedText
        displayedText
        description
      }
      comment {
        body
        created_at
        user {
          email
        }
      }
    }
    ... on PlainUrl {
      url {
        expandedText
        displayedText
        description
      }
    }
  }
}
```

Looks like the `... on <__typename` works already, but I'm not sure how to return different types from a resolver.

**Comment by donut** [comment]
Updated links:

- https://facebook.github.io/graphql/October2016/#sec-Interfaces
- https://facebook.github.io/graphql/October2016/#sec-Interface
- https://facebook.github.io/graphql/October2016/#sec-Field-Selections-on-Objects-Interfaces-and-Unions-Types
