### ISSUE TITLE
Use with Bucklescript

### ISSUE THREAD

**Issue by lpil** [andreas/ocaml-graphql-server#67]
Hello!

Apologies for the possibly silly newbie question: Is it possible to use the schema definition and query resolving part of this library with Bucklescript?

I'm asking as I'm writing a GraphQL OCaml application that runs on the Node runtime using Bucklescript. It is possible to use the Javascript GraphQL library for this but the type-safe design of this library is more attractive. :)

Cheers,
Louis

**Comment by wokalski** [comment]
Bucklescript support is work in progress. Check out graphql_ppx which has been built wit. Bucklescript in mind

**Comment by lpil** [comment]
Wonderful, thank you. Please feel free to close this issue

**Comment by andreas** [comment]
Do I get it right you want to make type-safe GraphQL requests from Bucklescript? If so, take a look at [`graphql_ppx'](https://github.com/mhallin/graphql_ppx/) as @wokalski mentions. If not, please reopen this issue and clarify :)

**Comment by lpil** [comment]
I wish to make a GraphQL server in Bucklescript as I'm targeting an environment where I can run Javascript code, but not native code.

It seems `graphql_ppx` is only suited for use in clients. :(

Could you re-open this issue please @andreas, I don't seem to be able to. Thank you

**Comment by andreas** [comment]
Ok, that makes sense. There are a couple of issues that need to be resolved before `ocaml-graphql-server` is Bucklescript-friendly:

- Currently `ocaml-graphql-server` makes use of OCaml v4.03-features (in particular [inline records](https://blog.janestreet.com/ocaml-4-03-everything-else/#inline-records)), while Bucklescript is tied to OCaml v4.02.3. Removing inline records should be a fairly mechanical task.
- A `bsconfig.json` would need to be defined.
- To run the tests, [`alcotest`](https://github.com/mirage/alcotest) would have to be Bucklescript-enabled (or you could disregard the tests).
- `ocaml-graphql-server` uses [`yojson`](https://github.com/mjambon/yojson) for JSON handling. This is not a blocker, but using `Js.Json` in Bucklescript would probably be more natural.

I'd welcome a PR which tries to do the above.

**Comment by wokalski** [comment]
Just a little note that removing inline records is not this mechanical (or my skills failed me). In particular heterogenous lists.

Also I’d consider if thIs task even makes sense. It might be that the output of bucklescript will be slow and you’d be better off binding to an existing Js library or running this one on native (which is probably the best option).

**Comment by lpil** [comment]
I'm more interested in just type safe the schema generation, once we have this the existing node lib can be used to resolve the queries. Perhaps it'd be a better idea to write a new library with a similar API that is intended for the purpose.

**Comment by lpil** [comment]
I think you're right. Thanks for the help :)
