### ISSUE TITLE
Union support

### ISSUE THREAD

**Issue by andreas** [andreas/ocaml-graphql-server#7]
See:

- https://facebook.github.io/graphql/#sec-Unions
- https://facebook.github.io/graphql/#sec-Union
- https://facebook.github.io/graphql/#sec-Field-Selections-on-Objects-Interfaces-and-Unions-Types

**Comment by donut** [comment]
Corrected links:

- https://facebook.github.io/graphql/October2016/#sec-Unions
- https://facebook.github.io/graphql/October2016/#sec-Union
- https://facebook.github.io/graphql/October2016/#sec-Field-Selections-on-Objects-Interfaces-and-Unions-Types
