### ISSUE TITLE
Dynamically constructing resolvers?

### ISSUE THREAD

**Issue by sgrove** [andreas/ocaml-graphql-server#73]
I know this is against the spirit (so far) of OGS, but we're hitting some limits on code-gen, and it'd be great for us to be able to define the graph in data and then generate the resolvers at startup time. I think this lines up with some of the ideas you've had around error handling/type checking for unions/interfaces, so maybe it's not quite so crazy.

Here's an example of what we'd like to be able to do (ideally with all the same type-checking benefits we've had before, but we're ok to move them from compile-time to runtime [in the form of startup time]) https://gist.github.com/sgrove/b3d5eaa64642e194896e2bef2d13adc8

**Comment by andreas** [comment]
We've talked about this use case via other channels, so I'll close the issue here.
