### ISSUE TITLE
Error in the example

### ISSUE THREAD

**Issue by mnewsha** [andreas/ocaml-graphql-server#84]
Hi,
I got this error trying to build the example:
```
File "server.ml", line 73, characters 2-14:
Error: Unbound module Server
```
What is wrong?

**Comment by grsabreu** [comment]
did you run jbuilder?

**Comment by mnewsha** [comment]
yes I ran jbuilder as ```jbuilder build server.exe``` and I got this error.

**Comment by mnewsha** [comment]
I have changed the second line from ```module C = Cohttp_lwt_unix``` to ```open Cohttp_lwt_unix``` and it worked but http://localhost:8080 seems not getting any response on client side

**Comment by andreas** [comment]
@mnewsha, I don't think #85 is not a correct fix. The example compiles correct for me with `graphql-lwt` version `0.5.0`. Could you please check your version of `graphql-lwt` (try `opam info graphql-lwt`)?

**Comment by mnewsha** [comment]
The version of graphql-lwt I'm using right now is 0.1.0 on OCaml 4.04.2 and unfortunately the available versions of the package for this version of OCaml are only 0.1.0 and 0.3.0 do you think upgrading to 0.3.0 can help? it needs some downgradings for cohttp and prometheus packages.
In fact I was trying to use ocaml-graphql-server with Ocsigen and I wrote this piece of code in a file ```message.eliom```:
```
open Graphql

type message = {
  msg : string;
}

let messages = [
  {msg = "Hello!"};
  {msg = "Bonjour!"};
  {msg = "Buongiorno!"}
]

let message = Schema.(obj "message"
  ~doc: "Message to be shown to user"
  ~fields: (fun _ -> [
    field "msg"
      ~doc: "Greeting for example"
      ~typ: (non_null string)
      ~args: Arg.[]
      ~resolve: (fun ctx c -> c.msg)
  ])
)

let schema = Schema.(schema [
  field "mssages"
    ~typ: (non_null (list (non_null message)))
    ~args: Arg.[]
    ~resolve:(fun ctx () -> messages)
])
```
I had this idea to use a part of the example on main page:
```
let query = Graphql_parser.parse "{ users(limit: $x) { name } }" in
let json_variables = Yojson.Basic.(from_string "{\"x\": 42}" |> Util.to_assoc) in
let variables = (json_variables :> (string * Graphql_parser.const_value) list)
Graphql.Schema.execute schema ctx ~variables query
```
although it is mysterious for me what is ```ctx``` exactly. I wanted to put it in an Ocsigen post service but it stopped me by this error:
```
File "src/message.eliom", line 13, characters 4-11:
Error: The type of this expression, ('_a, message option) Graphql.Schema.typ,
       contains type variables that cannot be generalized
Command exited with code 2.
```
line 13 is ```let message = Schema.(obj "message"``` it refers apparently to _a but I could not figure out what can it be. So I decided to learn from example but I got the mentioned error above. At the end I have to say that I could get a response from the fix.

**Comment by mnewsha** [comment]
In fact the newest version for graphql-lwt now is 0.3.0 and the newest version of graphql is 0.5.0 that is installed by opam on my machine too.

**Comment by andreas** [comment]
> The version of graphql-lwt I'm using right now is 0.1.0 on OCaml 4.04.2 and unfortunately the available versions of the package for this version of OCaml are only 0.1.0 and 0.3.0 do you think upgrading to 0.3.0 can help?

Ah yes, I mistakenly put `0.5.0` for `graphql-lwt`, when in fact I meant `0.3.0`. Version 0.3.0 introduces the `Graphql_lwt.Server` module which, according to the reported error message, is missing with your current version. I'm not sure why it would require a downgrade of cohttp -- I would be interested to know more about that.

Regarding your example, it looks correct to me. The error message `contains type variables that cannot be generalized` can be avoided in two ways as follows.

**Option 1**: Replacing `ctx` for `()` in the resolver
```diff
let message = Schema.(obj "message"
  ~doc: "Message to be shown to user"
  ~fields: (fun _ -> [
    field "msg"
      ~doc: "Greeting for example"
      ~typ: (non_null string)
      ~args: Arg.[]
-      ~resolve: (fun ctx c -> c.msg)
+      ~resolve: (fun () c -> c.msg)
  ])
)
```

**Option 2**: Adding a type annotation
```diff
-let message = Schema.(obj "message"
+let message : (unit, message option) Schema.typ = Schema.(obj "message"
  ~doc: "Message to be shown to user"
  ~fields: (fun _ -> [
    field "msg"
      ~doc: "Greeting for example"
      ~typ: (non_null string)
      ~args: Arg.[]
      ~resolve: (fun ctx c -> c.msg)
  ])
)
```

The parameter `ctx` is intended to be used when all resolvers in a schema need access to some request-specific information, e.g. the current user, a database connection pool or similar.

**Comment by guilhermedecampo** [comment]
something strange here in my configs 🤔 

![screen shot 2018-03-28 at 20 10 28](https://user-images.githubusercontent.com/4806269/38061093-29f8a50c-32c4-11e8-8aad-104826f11654.png)

**Comment by guilhermedecampo** [comment]
There is a step by step to know what's wrong in my environment?

**Comment by turboMaCk** [comment]
I've also ran into this issue.

in my case:
```
$ ocamlc --version
-> 4.06.1
$ opam info graphql graphql-lwt -f package,version
->         package: graphql
             version: 0.5.0
             package: graphql-lwt
             version: 0.1.0
$ cat /Users/{user}/.opam/system/lib/graphql-lwt/graphql_lwt.mli
-> (** GraphQL schema with Lwt support *)
module Schema : sig
  include Graphql_intf.Schema with type 'a io = 'a Lwt.t
end
```

**Comment by turboMaCk** [comment]
I've tried to force version of graphql-lwt to 0.3.0 but installation fails for me:

<img width="1920" alt="screen shot 2018-03-31 at 19 02 54" src="https://user-images.githubusercontent.com/2130305/38165602-442163c0-3516-11e8-982f-6d7d31a31f09.png">

**Comment by andreas** [comment]
Thanks @turbomack, it seems like a dependency resolution issue. I'll try look into it and get back to you.

**Comment by andreas** [comment]
@turboMaCk: It looks like the dependencies for `graphql-lwt` [were changed](https://github.com/ocaml/opam-repository/pull/10787), and I hadn't noticed. I've submitted a new version of `graphql` and `graphql-lwt` now with updated dependencies: https://github.com/ocaml/opam-repository/pull/11712

Once it's been merged, you should be able to install `graphql-lwt` version `0.6.0` and hopefully things will Just Work. In the meantime, you can try `opam pin add graphql-lwt --dev-repo`.

Thanks for sharing the install error.

**Comment by turboMaCk** [comment]
Thanks! I can confirm `opam pin add graphql-lwt --dev-repo` solved an issue - now I have it running 🙌 

Thanks for solving it so quickly. I'm glad my report was helpfull as this is first time I play with non-mirageOS based OCaml (and even Mirage was like just baby steps). Also thx for [great article](https://andreas.github.io/2018/01/05/modeling-graphql-type-modifiers-with-gadts/)

**Comment by guilhermedecampo** [comment]
awesome guys. I was out these days but gonna try soon the new approach.

**Comment by mnewsha** [comment]
Also I got this error when I tried to use the user example in the main page:
```
let query = Graphql_parser.parse "{ users { name } }" in
Graphql.Schema.execute schema (fun () -> ()) query
```
and the error for query:
```
Error: This expression has type (Graphql_parser.document, string) result
          but an expression was expected of type
          Graphql_parser.document = Graphql_parser.definition list
```
is there any conversion possible?

**Comment by turboMaCk** [comment]
@mnewsha I recommend you to read through default server implementation (https://github.com/andreas/ocaml-graphql-server/blob/master/graphql-lwt/src/graphql_lwt.ml#L5-L52)

in your case, you're interested in executing the query https://github.com/andreas/ocaml-graphql-server/blob/master/graphql-lwt/src/graphql_lwt.ml#L20-L21

and construction of query param https://github.com/andreas/ocaml-graphql-server/blob/master/graphql-lwt/src/graphql_lwt.ml#L30

**Comment by mnewsha** [comment]
Thanks! I'll check it out.

**Comment by mnewsha** [comment]
@andreas Thanks a lot!
