### ISSUE TITLE
Cannot compile when using a context to retrieve from db

### ISSUE THREAD

**Issue by joefiorini** [andreas/ocaml-graphql-server#86]
I'm trying out this library to see how it feels. My test is to see how hard it is to create a simple mutation and query to create and retrieve records in a postgres database. I have the query setup and working and now I'm trying to integrate it with Caqti. I'm very new to Ocaml (actually using Reason via esy, but I can read and translate ocaml well enough), so I may be suffering from some newbie errors.

I'm currently getting an error trying to compile my code (it's actually Reason code, but the problem seems to be agnostic of syntax):

```
Error: bin/Server.re:89:6-98:7
 86 ¦ let schema =
 87 ¦   Schema.(
 88 ¦     schema([
 89 ¦       io_field(
 90 ¦         "countdown",
 91 ¦         ~args=Arg.[arg("short", ~typ=non_null(string))],
 92 ¦         ~typ=countdown,

This type doesn't match what is expected.

This type: Graphql_lwt.Schema.field(unit, (module Caqti_lwt.CONNECTION))
Expecting: Graphql_lwt.Schema.field(unit, unit)

Extra info: Type (module Caqti_lwt.CONNECTION) is not compatible with type unit
```

My code is online here https://github.com/joefiorini/countdown-to/blob/reason/server/bin/Server.re.

I was wondering if anyone would mind posting an example of a query that uses a context to retrieve a value, preferable something a little more complex than a simple array (ie. Caqti's `find_opt` function returns an option wrapped in a result in an Lwt). I thought if I used an Lwt-supporting library I wouldn't have to do much wrapping/unwrapping, but that's turning out not to be true (ie. I still had to wrap my resolve result in `Lwt.return`).

**Comment by andreas** [comment]
> I'm currently getting an error trying to compile my code

I think there's a discrepancy between the `~ctx` argument you're passing to `Graphql_lwt.Server.start` [here](https://github.com/joefiorini/countdown-to/blob/reason/server/bin/Server.re#L115) (this appears to have type `unit -> (module Caqti_lwt.CONNECTION)`), and how you've declared your resolve functions, where `ctx` appears to be of type `unit` (e.g. [here](https://github.com/joefiorini/countdown-to/blob/reason/server/bin/Server.re#L93)).

> I thought if I used an Lwt-supporting library I wouldn't have to do much wrapping/unwrapping, but that's turning out not to be true (ie. I still had to wrap my resolve result in Lwt.return).

I'm guessing you're referring to this code: https://github.com/joefiorini/countdown-to/blob/reason/server/bin/Server.re#L94-L97. You should use [`>|=`](https://ocsigen.org/lwt/3.1.0/api/Lwt.Infix#VAL(>|=)) rather than `>>=` to avoid superfluous `Lwt.return`s (i.e. map rather than bind).

Hope this helps.

**Comment by joefiorini** [comment]
@andreas Thanks, the `>|=` tip is exactly what I needed for the wrapping, I should have noticed that myself, oops.

As for the `~ctx` argument, it looks like the default function for resolvers takes `'ctx, 'src` as the first two parameters, but when I tried to take `db` as the first parameter I got:

```
Error: bin/Server.re:94 28-30
 91 ¦ ~args=Arg.[arg("short", ~typ=non_null(string))],
 92 ¦ ~typ=countdown,
 93 ¦ ~resolve=(db, (), short) =>
 94 ¦ lookup_timer(short, db) >|= (fun
 95 ¦   | Ok(timer_opt) => timer_opt
 96 ¦   | Error(err) => None
 97 ¦   )

This type doesn't match what is expected.

This type: unit
Expecting: (module Caqti_lwt.CONNECTION)
```

So it seems that `unit` is being passed as the first arg, so I made `db` the second. Is my `~ctx` wrong? Should it _just_ be `db`?

**Comment by joefiorini** [comment]
I think that was what I was missing. I still had a bunch of `resolve` parameters in the `countdown` object definition that were missing the context param. I have it compiling now, thanks for the help!
