### ISSUE TITLE
GraphiQL returned for valid GET queries

### ISSUE THREAD

**Issue by brendanlong** [andreas/ocaml-graphql-server#89]
http://graphql.org/learn/serving-over-http/#get-request

Queries like this should work:

```
curl 'localhost:8080/graphql?query=%examples%7Bid%7D%7'
```

But instead I get the GraphiQL HTML page.

I think we need to make two changes:

 - Support reading the query from query params
 - Check accept headers for `text/html` before sending GraphiQL

**Comment by andreas** [comment]
I believe this was fixed by https://github.com/andreas/ocaml-graphql-server/pull/156.
