### ISSUE TITLE
Example server impl in graphql-lwt prevents using Lwt 4.0

### ISSUE THREAD

**Issue by anmonteiro** [andreas/ocaml-graphql-server#93]
As far as I understand, the only reason Cohttp is required in `graphql-lwt` is to implement the simple server that serves GraphiQL.

This prevents the usage of `graphql-lwt` with Lwt >= 4.0 because `cohttp-lwt-unix` required lwt < 4.0.

My suggestion would be to remove the example server to either the examples folder or a new package altogether. 

What do you think?

**Comment by hannesm** [comment]
I opened https://github.com/mirage/ocaml-cohttp/issues/621 -- hopefully we'll see a fresh cohttp-lwt-unix soon :)

**Comment by andreas** [comment]
Thanks for pointing this out. The server could indeed go into a separate package.

**Comment by anmonteiro** [comment]
The constraint on Lwt < 3.0.0 has been fixed with a release of Cohttp (https://github.com/mirage/ocaml-cohttp/issues/621)

**Comment by hannesm** [comment]
@anmonteiro yes, and that (cohttp 1.1.1) got recently merged into opam-repository https://github.com/ocaml/opam-repository/pull/12652
